import type { Metadata } from "next";
import { Raleway, Open_Sans } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"], display: "swap", variable: '--font-raleway' });
const openSans = Open_Sans({ subsets: ["latin"], display: "swap", variable: '--font-open-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.variable + ' ' + openSans.variable}>
        {children}
      </body>
    </html>
  );
}
